CREATE TABLE IF NOT EXISTS PH_TRAN_ASGNMT_DIM (
    TRAN_KEY INT UNSIGNED NOT NULL,
    CUST_KEY MEDIUMINT UNSIGNED NOT NULL,
    EMPLY_REL_FL CHAR(1) NOT NULL,
    PRIMARY KEY (TRAN_KEY) 
) ENGINE=InnoDB
;
