-- How to add index to temporary table?

CREATE TEMPORARY TABLE IF NOT EXISTS SAMPLE_CUST_KEY AS (
    SELECT 
        A.TRAN_KEY
        , B.CUST_KEY
    FROM PH_CUST_TRAN_ASGNMT_DIM AS A
    RIGHT JOIN (
        SELECT DISTINCT
            CUST_KEY
        FROM PH_CUST_TRAN_ASGNMT_DIM
        WHERE EMPLY_REL_FL <> 'Y'
        ORDER BY RAND() 
        LIMIT 10000
    ) AS B
    ON (A.CUST_KEY = B.CUST_KEY)
)
;

-- translate from tsql to mysql

CREATE TEMPORARY TABLE IF NOT EXISTS SAMPLE_CUST_SALES AS (
    SELECT
        A.CUST_KEY
        , CASE 
            WHEN (B.ORDER_NUM IS NOT NULL AND 
                  UPPER(B.ORDER_TYP_CD) = 'CUSTINITWEBORDER') THEN 'DIRECT'
            WHEN (B.ORDER_NUM IS NOT NULL AND 
                  UPPER(B.ORDER_TYP_CD) = 'CUSTINITPHONEORDER') THEN 'PHONE'
            ELSE 'FLS'
        END AS CHANNEL
        , EXTRACT(YEAR FROM B.BUS_DT) AS YR
        , EXTRACT(MONTH FROM B.BUS_DT) AS MNTH
        , 'DEMAND' AS CATEGORY
        , NULL AS VAL_STR
        , SUM(
            CASE
                WHEN B.TRAN_LINE_NET_AMT = 0.00 THEN B.TRAN_LINE_ORIGINAL_AMT
                ELSE B.TRAN_LINE_NET_AMT
            END
        ) AS VAL_NUM
    FROM SAMPLE_CUST_KEY AS A
    LEFT JOIN SLS_CUST_TRN_DTL_FCT AS B
    ON (A.TRAN_KEY = B.TRAN_KEY)
    WHERE 1 = 1
    AND B.UPC_IDNT IS NOT NULL
    AND (
        (B.TRAN_LINE_NET_AMT > 0.00 AND B.TRAN_LINE_ORIGINAL_AMT = 0.00) OR
        (B.TRAN_LINE_NET_AMT = 0.00 AND B.TRAN_LINE_ORIGINAL_AMT > 0.00) OR
        (B.TRAN_LINE_NET_AMT > 0.00 AND B.TRAN_LINE_ORIGINAL_AMT > 0.00)
    )
    AND B.BUS_DT < ADD_MONTHS(CURRENT_DATE - EXTRACT(DAY FROM CURRENT_DATE) + 1, 0)
)
;
